### ISSUE TITLE
ScheduledTask.xml encoding

### ISSUE THREAD

**Issue by c72578** [deajan/smartmontools-win#10]
The encoding of the file is UTF-8, but inside the file it says:
<?xml version="1.0" encoding="UTF-16"?>

Should be harmonized.

![xml_parsing_error](https://cloud.githubusercontent.com/assets/371551/14286159/6849d024-fb4e-11e5-8e0a-737c0f26f4b0.png)

**Comment by deajan** [comment]
Well there's nothing I can do about this, as Windows requires the file to have a UTF-16 header to be readable by schtasks.exe, but Inno Setup has no support for UTF-16 yet.

Anyway, as UTF-16 is an extension for wider symbols that aren't included in ScheduledTask.xml, this shouldn't be an issue.

**Comment by c72578** [comment]
Thanks for having a look at it.

**Comment by deajan** [comment]
Letting issue open for Python rewrite

**Comment by deajan** [comment]
Python rewrite happened for smartd configuration but we'll keep inno setup for the install. Closing.
