### ISSUE TITLE
Beta 6.5-1 misses MSVCR100.dll

### ISSUE THREAD

**Issue by deajan** [deajan/smartmontools-win#11]
Fresh win7 x64 complains abut missing MSVCR100.dll that should have come with py2exe build

**Comment by mitar** [comment]
Any workaround? I tried installing [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53840) but it didn't help.

**Comment by deajan** [comment]
Should have resolved that since a moment.
As for now, you may download Microsoft Visual C++ 2010 SP1 redist x86 package which should include the file (yes, x86 version because python executables aren't x64 event on x64 systems).

**Comment by deajan** [comment]
Added msvcr100.dll to installer (x86 version only)

**Comment by deajan** [comment]
Fixed in RC
