### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by seanvree** [deajan/smartmontools-win#13]
Love this tool guys. 

Got the service install, working great. 

Am I missing something or how do I actually get to the GUI?  I'm not sure what file it is?

THX!

**Comment by deajan** [comment]
If you installed latest v6.5-1, the GUI should popup at the end of the install process. There are also two new links in the start menu for configuring smartd and erroractions.
The GUI itself installs to %programfiles%\smartmontools for Windows\bin\"smartd-pyngui-erroraction.

**Comment by seanvree** [comment]
@deajan  - got it!

I can launch the smartd_pyngui.exe, but  when I launch the C:\Program Files\smartmontools for Windows\bin\smartd-pyngui-erroraction\ erroraction_config.exe I get these errors:

```
2017-05-11 02:57:42,732 :: DEBUG :: Registered property modal
2017-05-11 02:57:42,739 :: DEBUG :: Registered property image
2017-05-11 02:57:42,739 :: DEBUG :: Registered property type
2017-05-11 02:57:42,739 :: DEBUG :: Registered property path
2017-05-11 02:57:42,739 :: DEBUG :: Registered property textvariable
2017-05-11 02:57:42,742 :: INFO :: Running on python 3.4.4 / uname_result(system='Windows', node='VreePlexDesktop', release='10', version='10.0.14393', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
2017-05-11 02:57:42,742 :: WARNING :: Warning: This is an unstable developpment version.
2017-05-11 02:57:42,742 :: CRITICAL :: Wrong configuration file path provided.
Wrong configuration file path provided.
```

**Comment by deajan** [comment]
Are you sure you're running latest version ? The debug code of the GUI isn't enabled in that build normally.
Also, can you post your erroraction_config.cmd file (with password replaced by asterisks) ?

**Comment by seanvree** [comment]
Yeah, running the latest version
```
C:\Users\Administrator>cd C:\Program Files\smartmontools for Windows\bin

C:\Program Files\smartmontools for Windows\bin>smartctl.exe
smartctl 6.5 2016-05-07 r4318 [x86_64-w64-mingw32-win10] (sf-6.5-1)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

ERROR: smartctl requires a device name as the final command-line argument.


Use smartctl -h to get a usage summary


C:\Program Files\smartmontools for Windows\bin>
```
It's completely blank right now:

```
:: This file was generated on 2017-05-11 02:55:11.135094 by erroraction_config 0.2
:: http://www.netpower.fr
SET SMTP_SERVER=
SET MAILER=mailsend
SET LOCAL_ALERT=yes
SET SMTP_USER=
SET SECURITY=none
SET DESTINATION_MAIL=
SET SMTP_PASSWORD=
SET SMTP_PORT=25
SET SOURCE_MAIL=
SET WARNING_MESSAGE=WARNING: One of your hard disks has SMART errors. Please write down this message and contact your technical support as soon as possible.

SET COMPRESS_LOGS=no
SET MAIL_ALERT=no
```

**Comment by deajan** [comment]
What version of smartmontools-win package did you use ?

**Comment by seanvree** [comment]
@deajan  - Not completely sure now, was a month or so ago I installed?  How can I tell?

**Comment by deajan** [comment]
Okay, a month ago there only was a beta.
Please install latest executable from http://netpower.fr/smartmontools-win

**Comment by seanvree** [comment]
@deajan - yup, much better!

THX!
