### ISSUE TITLE
dev version 6.5.2 does not install some files in unattended mode - write access not allowed?

### ISSUE THREAD

**Issue by zhladik** [deajan/smartmontools-win#14]
missing files:
scheduled_send.cmd
ScheduledTask.xml
mailsend.exe
fix_badsectors.cmd
base64.exe
dd.exe
gzip.exe

may be bacause pingui dir renamed?

**Comment by deajan** [comment]
This depends on the command-line you used to install.
As the current dev version changed component names from earlier version, the command-line in README file isn't correct anymore for dev version. I'll update on release.

In the meanwhile, here's the list of all components than can be installed:

```smartmontools-win-6.5-2-dev.exe /COMPONENTS="core,core\service,core\service\gui,core\service\mailalert,core\service\localalert,core\scheduledtestalerts,core\regext,core\regext\info,core\regext\tests,core\updatedb,fixbadsecttools,authorlinks,statistics" /SUPPRESSMSGBOXES /SILENT```

Installing only the smartd_pyngui GUI would require to change all those components to ```smartdpyngui```

Does this answer your question ?

**Comment by zhladik** [comment]
Thanks for fast answer,

I estimated some missing components in components list, but I was 
not sure.


On your last mail I suppose all components listed, but 
smartdpyngui ommited by mistake?
So this line  si complete:

 
/COMPONENTS="core,core\service,core\service\gui,core\service\mailalert,core\service\localalert,core\scheduledtestalerts,core\regext,core\regext\info,core\regext\tests,core\updatedb,fixbadsecttools,authorlinks,statistics" 
...


May be ISS config allows some wildcards?:

/COMPONENTS="core,core\*,...

or

/COMPONENTS="*"

I ahve not experinece wit Innosetup, but some simplification can 
be nice

                              Zdenek Hladik



Dne 22.5.2017 v 12:17 Orsiris de Jong napsal(a):

**Comment by deajan** [comment]
Since core\service\gui and smartdpyngui are the same but mutually exclusive (you can install smartdpyngui without any other component for using it with upstream package), you shouldn't use wildcards.

You can also use default setup, just don't use the /COMPONENTS switch then.

**Comment by deajan** [comment]
Closed due to inactivity
