### ISSUE TITLE
Error message:  " ATA CHECK POWER STATUS" ??

### ISSUE THREAD

**Issue by seanvree** [deajan/smartmontools-win#17]
What does this error mean:

"smartd[19112]:CRIT: Device: /dev/sdf [SAT], no ATA CHECK POWER STATUS support, ignoring -n Directive"

Thanks!

**Comment by seanvree** [comment]
@deajan  - so how do I suppress those warnings?

**Comment by deajan** [comment]
Well... Read the link I sent you...

**Comment by seanvree** [comment]
@deajan ... Sure, it says:

"There is currently no text in this page. You can search for this page title in other pages, or search the related logs, but you do not have permission to create this page."

**Comment by c72578** [comment]
There is a dot at the end of the hyperlink:
[https://wiki.archlinux.org/index.php/S.M.A.R.T.](https://wiki.archlinux.org/index.php/S.M.A.R.T.)

**Comment by seanvree** [comment]
Thx!

**Comment by deajan** [comment]
@c72578 Thx :)

**Comment by slrslr** [comment]
On Linux, [someone suggest](https://unix.stackexchange.com/a/111407) to add line "/dev/sdf -d ignore" to file /etc/smartd.conf yet in manual page -d means debug. smartd 7.2 2020-12-30 r5155 (Debian, stable package)
So how do you exclude power status check for /dev/sdf to get rid of red journal warning, please:
`smartd[1326]: Device: /dev/sdf [SAT], no ATA CHECK POWER STATUS support, ignoring -n Directive`

**Comment by tkna91** [comment]
@slrslr Remove the description `-n POWERMODE[,N][,q]` from the configuration of the corresponding device in `/etc/smartd.conf`.
https://www.smartmontools.org/wiki/Powermode
