### ISSUE TITLE
When installed in WinXP 32bit, does not start

### ISSUE THREAD

**Issue by mx-lin** [deajan/smartmontools-win#21]
Both smartd_pyngui.exe and erroraction_config.exe do not start with a popup indicating "Not a Win32 application". Is it for 64bit Windows?

**Comment by deajan** [comment]
Hello,
It would be nice to know which version you have tested.

**Comment by mx-lin** [comment]
Salut, 

version 
smartmontools-win-6.6-1.exe
telecharge ce matin depuis netpower.fr

A+
Michel

You wrote on Tuesday, April 24, 2018, 7:55:44 AM:

> Hello,
> It would be nice to know which version you have tested.
> —

**Comment by deajan** [comment]
I must admit that I didn't really test 6.6-1 on XP...
And... yes, I can confirm that it doesn't work on XP.
I quickly ran a dependancy walker on the exe, which are indeed 32 bits. I'll need to investigate further.
Nevertheless, I won't officially support XP anymore.
