### ISSUE TITLE
Bug in smartd service detection

### ISSUE THREAD

**Issue by maxdevaine** [deajan/smartmontools-win#27]
Hi,
if I manually uninstall smartd service (I tryeing silent uninstall your tool, but one window still popup), then uninstallation program give back :

"There is a smartd service is installed which does not seem to belong to smartmontools-win. Do you want to uninstall it ?"

I think problem is with this code "smartmontools for Windows includes.iss":

`ShellExec('', ExpandConstant('{cmd}'), ExpandConstant('/C {sys}\sc.exe qc ' + srv + ' | findstr "BINARY_PATH_NAME" | findstr /C:"\\smartmontools for Windows\\"'), '', SW_HIDE, ewWaitUntilTerminated, resultcode);`

You trying find english name, but Windows translate most of internal strings.
So, in another language does not exist name "BINARY_PATH_NAME".

BTW, I would like to completly clear some PC, I do no want to stop using your tools. It is very nice and useful. Thanks for your work.

Max
PS: I think I have now only one option to uinstall this program in silent mode, force remove all from directories and from registry via own batch file, or do you have any other idea?

**Comment by deajan** [comment]
Fixed, with only a 2 years delay ;(
