### ISSUE TITLE
Support for e-mail password with space

### ISSUE THREAD

**Issue by sagsagman** [deajan/smartmontools-win#6]
Using an e-mail password that contains a space fails, at least when sending a test e-mail during the installation procedure of the smartmontools-win package.

A space is a valid character for passwords with most e-mail providers.

When clicking to send the test e-mail, the resulting error suggests the password field is not enclosed with quotes ("... pass ..."), when executing sendemail.exe to send the e-mail.

**Comment by deajan** [comment]
Are you sure you're using sendemail instead of mailsend ?

**Comment by sagsagman** [comment]
Sorry, you're right, it was probably mailsend. Anyhow, I haven't changed the default mail sender, I just input source/destination/server fields.

**Comment by deajan** [comment]
Well i'll have quick look one i'll have setup an email address somewhere with a plain space in the password.

**Comment by sagsagman** [comment]
Just for your reference, I'd like to stress again that I suspect the problem is simply lack of double quotes around the password field in the command line.

Thank you very much for your attention.

**Comment by deajan** [comment]
I guess so, but then i have to check the scripts too, the password encryption, etc.

**Comment by sagsagman** [comment]
Of course, any change is needed to be tested thoroughly.

I've already worked around this problem in my setup, but I felt I should open an issue here so that people are aware of this particular shortcoming.
Otherwise, the software works well for me.

Thanks again.

**Comment by deajan** [comment]
Could you please test the following build ? (including both mailers, in gui setup and by running erroraction.cmd script once installed)

http://netpower.fr/projects/smartmontools/smartmontools-win-6.4-3-beta.exe

**Comment by sagsagman** [comment]
Should I provide any arguments to erroraction.cmd when running it, or can it run without any arguments?

**Comment by deajan** [comment]
When installed, it will read erroraction_config.cmd with everything it needs, according to your installation.
You may change the mailer directly in erroraction_config.cmd to test mailsend and sendemail.

**Comment by deajan** [comment]
Of course i could have given you the right link... Corrected
http://netpower.fr/projects/smartmontools/smartmontools-win-6.4-3-testing.exe

**Comment by sagsagman** [comment]
OK, during installation, test e-mail now goes through well both with mailsend and sendemail.

Running erroraction.cmd however, it works only with sendemail.

When MAILER=mailsend, I get the following output from erroraction.cmd:
> Error: MAIL FROM failed: '530 5.7.0 Must issue a STARTTLS command first. di7sm3312406wib.23 - gsmtp'
> Could not send mail
> Something bad happened while executing this script. Please check log file. You can also check what happens with parameter --dryrun

In erroraction.log, the following lines are added:
> Configuration file check success. 
> Sending mail using mailsend failed.

**Comment by deajan** [comment]
Could you please send me the content of erroraction_config.cmd (of course, replace your password string).
Also, for mailsend and sendemail, could you please give me the output of the following command
```
erroraction.cmd --dryrun
```

Thanks.

**Comment by sagsagman** [comment]
erroraction_config.cmd:
> set MAIL_ALERT=yes
> set MAILER=sendemail
> set SOURCE_MAIL=xxxxxxxxxxxx@gmail.com
> set DESTINATION_MAIL=yyyyyyyyyyyyy@gmail.com
> set SMTP_SERVER=smtp.gmail.com
> set SMTP_PORT=587
> set SMTP_USER=xxxxxxxxxxxx@gmail.com
> set SMTP_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> set SECURITY=tls
> set LOCAL_ALERT=no
> set WARNING_MESSAGE=WARNING: One of your hard disks has SMART errors. Please write down this message and contact your technical support as soon as possible.
> set COMPRESS_LOGS=yes
> set DEVICE_LIST=DEVICESCAN
> set SMART_LOG_FILE=C:\Program Files (x86)\smartmontools for Windows\smart.log
> set ERROR_LOG_FILE=C:\Program Files (x86)\smartmontools for Windows\erroraction.log
> set PROGRAM_PATH=C:\Program Files (x86)\smartmontools for Windows


sendemail dry run:
> "C:\Program Files (x86)\smartmontools for Windows\bin\sendemail.exe" -f "xxxxxxxxxxxxxxxx@gmail.com" -t "yyyyyyyyyyyyyyyyy@gmail.com" -u "Smart Error on RECOVER-PC.RECOVER-PC" -m "Wed 07/01/2015 - WARNING: One of your hard disks has SMART errors. Please write down this message and contact your technical support as soon as possible." -a "C:\Program Files (x86)\smartmontools for Windows\smart.log.gz" -s smtp.gmail.com:587 -o tls=yes -xu "xxxxxxxxxxxxxxxx@gmail.com" -xp "yyyy yyyyyyyyy yyyyyyyyy"


mailsend dry run:
> "C:\Program Files (x86)\smartmontools for Windows\bin\mailsend.exe" -f "xxxxxxxxxxxxxxxx@gmail.com" -t "yyyyyyyyyyyyyyyyy@gmail.com" -sub "Smart Error on RECOVER-PC.RECOVER-PC" -M "Wed 07/01/2015 - WARNING: One of your hard disks has SMART errors. Please write down this message and contact your technical support as soon as possible." -attach "C:\Program Files (x86)\smartmontools for Windows\smart.log.gz" -smtp "smtp.gmail.com" -port 587 -auth -user "xxxxxxxxxxxxxxxx@gmail.com" -pass "yyyy yyyyyyyyy yyyyyyyyy"

**Comment by deajan** [comment]
Got it. Bad variable name. Every mail related issue should be fixed now with the following build.
http://netpower.fr/projects/smartmontools/smartmontools-win-6.4-3-testing2.exe

**Comment by sagsagman** [comment]
Looks okay now, thanks for the fast response.
BTW, which is preferable, mailsend or sendemail?

**Comment by deajan** [comment]
I added mailsend because it's more compatible with some esotheric mail servers :) I just kept sendemail as a backup solution.
