### ISSUE TITLE
False positive email after system boot when using Seagate disk

### ISSUE THREAD

**Issue by quietscheente** [deajan/smartmontools-win#7]
I'm using this great software to monitor the smart value of the disks on several windows machines. It works quite well. But a few weeks ago I installed a Seagate disk to one of my machines and since that I always get a SMART warning directly after booting this machine.
I'm not sure if it's an issue related to smartmontools for windows. It seems to be a problem with the temperature value that is provided by this Seagate disk. I somewhere read, that Seagate uses some weird temperature values. Perhaps you can tell me, how to overcome these problems. The SMART status of the Seagate disk right after booting the machine is the following:
<pre>=== START OF INFORMATION SECTION ===
Model Family:     Seagate Barracuda 7200.14 (AF)
Device Model:     ST1000DM003-1ER162
Serial Number:    XXXXXXXX
LU WWN Device Id: X XXXXXX XXXXXXXXX
Firmware Version: CC45
User Capacity:    1.000.204.886.016 bytes [1,00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2, ACS-3 T13/2161-D revision 3b
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Wed Jun 10 08:16:47 2015 MS
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED
See vendor-specific Attribute list for marginal Attributes.

(...)

SMART Attributes Data Structure revision number: 10
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000f   119   099   015    Pre-fail  Always       -       206334736
  3 Spin_Up_Time            0x0003   097   097   003    Pre-fail  Always       -       0
  4 Start_Stop_Count        0x0032   100   100   050    Old_age   Always       -       8
  5 Reallocated_Sector_Ct   0x0033   100   100   051    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000f   069   060   015    Pre-fail  Always       -       8271071
  9 Power_On_Hours          0x0032   099   099   050    Old_age   Always       -       1433
 10 Spin_Retry_Count        0x0013   100   100   019    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   050    Old_age   Always       -       8
183 Runtime_Bad_Block       0x0032   100   100   050    Old_age   Always       -       0
184 End-to-End_Error        0x0032   100   100   050    Old_age   Always       -       0
187 Reported_Uncorrect      0x0032   100   100   050    Old_age   Always       -       0
188 Command_Timeout         0x0032   100   100   050    Old_age   Always       -       0 0 0
189 High_Fly_Writes         0x003a   100   100   058    Old_age   Always       -       0
190 Airflow_Temperature_Cel 0x0022   072   065   034    Old_age   Always       -       28 (Min/Max 24/35)
191 G-Sense_Error_Rate      0x0032   100   100   050    Old_age   Always       -       0
192 Power-Off_Retract_Count 0x0032   100   100   050    Old_age   Always       -       0
193 Load_Cycle_Count        0x0032   098   098   050    Old_age   Always       -       4200
194 Temperature_Celsius     0x0022   028   040   034    Old_age   Always   FAILING_NOW 28 (0 17 0 0 0)
197 Current_Pending_Sector  0x0012   100   100   018    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0010   100   100   016    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x003e   200   200   062    Old_age   Always       -       0
240 Head_Flying_Hours       0x0000   100   253   000    Old_age   Offline      -       1425h+26m+54.634s
241 Total_LBAs_Written      0x0000   100   253   000    Old_age   Offline      -       1444958427
242 Total_LBAs_Read         0x0000   100   253   000    Old_age   Offline      -       14382033185</pre>

**Comment by deajan** [comment]
Well this is indeed not a smartmontools-win problem. You may ignore temperature changes by specifying -I194 in smartd.conf while getting a fix.
You should ask this on the smartmontools-support@lists.sourceforge.net support list.
